apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: jupyter
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  containers:
    - name: jupyter
      image: jupyter/base-notebook:${jupyter_version}
      ports:
      - containerPort: 8888
        protocol: TCP
        name: http
      volumeMounts:
        - mountPath: /root
          name: notebook-volume
  volumes:
  - name: notebook-volume
    gitRepo:
      repository: "https://github.com/kubernetes-client/python.git"
