# NOTE: Replace ${GCLOUD_PROJECT} with your gcloud project id.
#       Replace ${SERVICE_NAME} with gRPC service name. Example: testbed.endpoints.${GCLOUD_PROJECT}.cloud.goog
apiVersion: v1
kind: Service
metadata:
  name: testbed-api
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: testbed-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbed-api
  template:
    metadata:
      labels:
        app: testbed-api
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--backend=grpc://127.0.0.1:50051",
          "--service=testbed-api.endpoints.$$GCP_PROJECT_ID$$.cloud.goog",
          "--rollout_strategy=managed",
        ]
        ports:
          - containerPort: 9000
      - name: testbed-api-server
        image: gcr.io/$$GCP_PROJECT_ID$$/testbed-server:latest
        ports:
          - containerPort: 50051
