apiVersion: batch/v1
kind: Job
metadata:
  name: testbed-deployer
spec:
  template:
    spec:
      containers:
      - name: testbed-deployer
        image: gcr.io/$$GCP_PROJECT$$/testbed-deployer:latest
        command:
        - java
        args:
        - -jar
        - /deployer/deployer.jar
        - --app_name
        - unauthenticated_jupyter
        - --config_path
        - /deployer/application
        - --template_data
        - ""
      restartPolicy: Never
  backoffLimit: 1
