apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: jupyter
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter
        tier: frontend
    spec:
      containers:
      - name: jupyter
        image: jupyter/base-notebook:${jupyter_version}
        ports:
        - containerPort: 8888
        command: [ "start-notebook.sh" ]
        args: [ "--NotebookApp.token='${notebook_token}'" ]
