type: google.api.Service
config_version: 3

#
# Name of the service configuration.
# NOTE: Replace $$GCP_PROJECT_ID$$ with your gcloud project id.
#
name: testbed-api.endpoints.$$GCP_PROJECT_ID$$.cloud.goog

#
# API title to appear in the user interface (Google Cloud Console).
#
title: Testbed gRPC API
apis:
- name: tsunami.security.scanner.utilities.TsunamiTestbed
